src/Entity/Operation.php
<?php

namespace App\Entity;

use App\Repository\OperationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OperationRepository::class)
 */
class Operation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numeroOperation;

    /**
     * @ORM\Column(type="date")
     */
    private $dateOperation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $montant;

    /**
     * @ORM\ManyToOne(targetEntity=Compte::class, inversedBy="operations")
     */
    private $compte;

    /**
     * @ORM\ManyToOne(targetEntity=TypeOperation::class, inversedBy="operations")
     */
    private $type_Operation;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="operations")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroOperation(): ?string
    {
        return $this->numeroOperation;
    }

    public function setNumeroOperation(string $numeroOperation): self
    {
        $this->numeroOperation = $numeroOperation;

        return $this;
    }

    public function getDateOperation(): ?\DateTimeInterface
    {
        return $this->dateOperation;
    }

    public function setDateOperation(\DateTimeInterface $dateOperation): self
    {
        $this->dateOperation = $dateOperation;

        return $this;
    }

    public function getMontant(): ?string
    {
        return $this->montant;
    }

    public function setMontant(string $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getCompte(): ?Compte
    {
        return $this->compte;
    }

    public function setCompte(?Compte $compte): self
    {
        $this->compte = $compte;

        return $this;
    }

    public function getTypeOperation(): ?TypeOperation
    {
        return $this->type_Operation;
    }

    public function setTypeOperation(?TypeOperation $type_Operation): self
    {
        $this->type_Operation = $type_Operation;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/OperationType.php
<?php

namespace App\Form;

use App\Entity\Operation;
use App\Entity\TypeOperation;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ResetType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OperationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            //->add('numeroOperation')
            //->add('dateOperation')
            ->add('montant',TextType::class,array('label'=>'Montant','required'=>False, 'attr'=>array('class'=>'form-control form-group')))
            //->add('compte')
            ->add('type_Operation', EntityType::class,array('class'=>TypeOperation::class,'label'=>'Type Operation', 'attr'=>array('class'=>'form-control form-group')))
            ->add('Valider', SubmitType::class, array('attr'=>array('class'=>'btn btn-success form-group')))
            ->add('Annuler', ResetType::class, array('attr'=>array('class'=>'btn btn-danger form-group')))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Operation::class,
        ]);
    }
}

src/Controller/OperationController.php
<?php

namespace App\Controller;

use App\Entity\Compte;

use App\Entity\Operation;
use App\Form\OperationType;
use App\Form\RechercheCompteType;
use App\Form\VirementType;
use App\Repository\CompteRepository;
use App\Repository\OperationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class OperationController extends AbstractController
{
    /**
     * @Route("/operation", name="operation")
     */
    public function index()
    {
    
        $p=new Compte();
        $o=new Operation();
        $form = $this->createForm(RechercheCompteType::class, $p, array('action'=>$this->generateUrl('recherche_compte')));
        $data['form'] = $form->createView();

        $forms = $this->createForm(VirementType::class, $o, array('action'=>$this->generateUrl('recherche_compteVirement')));
        $data['forms'] = $forms->createView();

        return $this->render('operation/index.html.twig',$data);
    }
     /**
     * @Route("/operation/recherche", name="recherche_compte")
     */
    public function search(Request $request, CompteRepository $repository)
    {

        $c = new Compte();
        $form = $this->createForm(RechercheCompteType::class, $c);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
           $numCpt = $form->get('numeroCompte')->getData();  
            
            $em = $this->getDoctrine()->getManager();
           
            $id = $repository->getIdCpt($numCpt);
            if ($id!=null){
            $s = new Operation();
            $form = $this->createForm(OperationType::class, $s, array('action'=>$this->generateUrl('operation_add', ['id' => $id])));
            $data['form'] = $form->createView();       
        
            $data['compte'] = $em->getRepository(Compte::class)->find($id);
   
    $data['operations'] = $em->getRepository(Operation::class)->findBy(['compte'=>$id]);
    return $this->render('operation/liste.html.twig',$data);
            }else{
                 
                $p=new Compte();
                $o=new Operation();
                $form = $this->createForm(RechercheCompteType::class, $p, array('action'=>$this->generateUrl('recherche_compte')));
                $data['form'] = $form->createView();

                $forms = $this->createForm(VirementType::class, $o, array('action'=>$this->generateUrl('recherche_compte')));
                $data['forms'] = $forms->createView();

                $data['error_message'] = 'ce Compte n\'existe pas !';
                return $this->render('operation/index.html.twig',$data);
            } 
        }
    }

    /**
     * @Route("/Operation/edit/{id}", name="operation_edit")
     */
    public function edit($id,OperationRepository $repository)
    {
        $em = $this->getDoctrine()->getManager();
        $p=new Operation();
        $s=new Compte();
        $form = $this->createForm(OperationType::class, $p, array('action'=>$this->generateUrl('operation_add', ['id' => $id])));//ajouter id en parametre de operation_add se referer a ajoutCompte() ds compte controller
        $data['form'] = $form->createView();
         
        $data['compte'] = $em->getRepository(Compte::class)->find($id);
        //ok ligne35 $data['operations'] = $em->getRepository(Operation::class)->findAll($id);//pour le moment récupere tte les operations or doit recuperer operation compte correspondant
        $data['operations'] = $em->getRepository(Operation::class)->findBy(['compte'=>$id]);
        
        return $this->render('operation/liste.html.twig',$data);
        
    }

    /**
     * @Route("/Operation/add/{id}", name="operation_add")
     */
    public function add(Request $request,$id,OperationRepository $repository)
    {
        $em = $this->getDoctrine()->getManager();
        $c = new Operation();
        $form = $this->createForm(OperationType::class, $c);
        
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $c = $form->getData();
            $c->setCompte($em->getRepository(Compte::class)->find($id));
            $dateOperation = new \Datetime();
            $c->setDateOperation($dateOperation);
            
            $lastid = $repository->getMaxId();//getMaxId() fonction créer dans OperationRepository
            $c->setNumeroOperation($lastid);
            $c->setUser($this->getUser());
    

           // $em->persist($c);
            //$em->persist($c->getEmployeur()); soit cette ligne ou cascade={"persist"} au  niveau de l'entité
            //$em->flush();
             //update solde compte apres une operation de depot
             if ($c->getTypeOperation()=='depot'){
                $p =$em->getRepository(Compte::class)->find($c->getCompte()->getId());
                $solde = $p->getSolde() + $c->getMontant();
                $p->setSolde($solde);
                $em->flush();
                $s = new Operation();
                        $form = $this->createForm(OperationType::class, $s, array('action'=>$this->generateUrl('operation_add', ['id' => $id])));
                        $data['form'] = $form->createView();       
                    
                        $data['compte'] = $em->getRepository(Compte::class)->find($id);
                        $em->persist($c);
            
                        $em->flush();
                $data['success_message'] = 'Operation de depot éffectuée avec succès';
                $data['operations'] = $em->getRepository(Operation::class)->findBy(['compte'=>$id]);
                return $this->render('operation/liste.html.twig',$data);
                
            }
            elseif($c->getTypeOperation()=='retrait'){
                     
                $soldeC = $c->getMontant();
                $p =$em->getRepository(Compte::class)->find($c->getCompte()->getId());
                if($p->getEtatCompte()=='actif'){
                    if ($p->getSolde() < $c->getMontant()){
                        $s = new Operation();
                        $form = $this->createForm(OperationType::class, $s, array('action'=>$this->generateUrl('operation_add', ['id' => $id])));
                        $data['form'] = $form->createView();       
                    
                        $data['compte'] = $em->getRepository(Compte::class)->find($id);
                        $data['error_message'] = 'Le solde de votre compte est inférieur à '.$soldeC;
                        $data['operations'] = $em->getRepository(Operation::class)->findBy(['compte'=>$id]);
                        return $this->render('operation/liste.html.twig',$data);
                    }else{
                
                        $solde = $p->getSolde() - $c->getMontant();
                        $p->setSolde($solde);
                        $em->flush();
                            $s = new Operation();
                            $form = $this->createForm(OperationType::class, $s, array('action'=>$this->generateUrl('operation_add', ['id' => $id])));
                            $data['form'] = $form->createView();       
                        
                            $data['compte'] = $em->getRepository(Compte::class)->find($id);
                            $em->persist($c);
            
                            $em->flush();
                            $data['reatrait_message'] = 'Operation de retrait éffectuée avec succès';
                            $data['operations'] = $em->getRepository(Operation::class)->findBy(['compte'=>$id]);
                            return $this->render('operation/liste.html.twig',$data);
                        }
                    }else{
                        $s = new Operation();
                        $form = $this->createForm(OperationType::class, $s, array('action'=>$this->generateUrl('operation_add', ['id' => $id])));
                        $data['form'] = $form->createView();       
                    
                        $data['compte'] = $em->getRepository(Compte::class)->find($id);
                        $data['bloquer_message'] = 'Ce compte est bloqué ! opération de retrait impossible';
                        $data['operations'] = $em->getRepository(Operation::class)->findBy(['compte'=>$id]);
                        return $this->render('operation/liste.html.twig',$data);
                    }
                        
            }
        }
     
        //return $this->redirectToRoute('operation_edit', ['id' => $id]);
    }

    /**
     * @Route("/operation/virement", name="recherche_compteVirement")
     */
    public function searchVirement(Request $request, CompteRepository $repository)
    {

        return $this->redirectToRoute('operation');
    }

}

templates/operation/index.html.twig
{% extends 'accueil.html.twig' %}
{%block glyficon%}
<link href="{{ asset('modaal/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
<script src="{{ asset('modaal/bootstrap.min.js') }}"></script>
<script src="{{ asset('modaal/jquery-3.2.1.min.js') }}"></script>



<style>
  .modal-header, h4, .close {
    background-color: #5cb85c;
    color:white !important;
    text-align: center;
    font-size: 30px;
  }
  .modal-footer {
    background-color: #f9f9f9;
  }
  </style>
{% endblock%}
{% block title %}Gestion operation{% endblock %}

{% block body %}
<div></br></br></div>
<div class="container col-md-12">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
        Virement Bancaire
    </button>
</div>

<div><br><br><br><br></div>
<div class="container col-md-6">
    <div class="card ">
        <div class="card-header">Entrer Numero Compte du client</div>
        <div class="card-body">
                {% if error_message is defined %}
                     <div class="alert alert-danger">{{ error_message  }}</div>
                {% endif %}
    {{form(form)}}
  </div>   
    </div>
    </div>
    <div><br><br></div>
    <div></br></br></div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Formulaire Virement </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
            <div class="container col-md-8">
                <div class="card ">
                    <div class="card-header"><center style="color:red;">Veuillez renseigner ces champs !</center></div>
                        <div class="card-body">
                     {{form(forms)}}
                        </div>   
                </div> 
            </div>
</div>
      </div>
      <div class="modal-footer">
        <div class="container my-auto">
  <div class="copyright text-center my-auto">
    <span>Copyright &copy; Banque-du-Peuple 2020</span>
  </div>
</div>
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>
<div><br><br></div>
    <div></br></br></div>
{% endblock %}

templates/operation/liste.html.twig
{% extends 'accueil.html.twig' %}

{% block title %}Gestion operation{% endblock %}

{% block body %}

<div></br></br></div>
<div class="row">

        <div class="container col-md-8">
            <div class="card ">
                <div class="card-header"><center style="color:red;">infos compte</center></div>
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                         <th>NUMERO COMPTE</th>
                            <th>TYPE COMPTE</th>
                            <th>SOLDE</th>
                            <th>NOM CLIENT</th>  
                        </tr>
                        <tr>
                            <td>{{ compte.getNumeroCompte() }}</td>
                            <td>{{ compte.getTypeCompte() }}</td><!-- y'a une fonction toString() qui retourne le libelle ds l'entité typeCompte  -->
                               
                            <td>{{ compte.getSolde() }}</td>
                            <td>{{ compte.getClient().getNom() }} {{ compte.getClient().getPrenom() }}</td>
                               
                        </tr>
                            
                    </table>        
                </div>   
            </div>
        </div>
    </div>
<div></br></br></br></br></div>
<div class="row">
        
            <div class="container col-md-8">
                <div class="card ">
                    <div class="card-header"><center style="color:red;">Nouvelle operation </center></div>
                        <div class="card-body">

                        {% if error_message is defined %}
                            <div class="alert alert-danger">{{ error_message  }}</div>
                        {% endif %}
                        {% if success_message is defined %}
                            <div class="alert alert-success">{{ success_message  }}</div>
                        {% endif %}
                        {% if reatrait_message is defined %}
                            <div class="alert alert-success">{{ reatrait_message  }}</div>
                        {% endif %}
                        
                         {% if bloquer_message is defined %}
                            <div class="alert alert-danger">{{ bloquer_message  }}</div>
                        {% endif %}
                        
                        {{ form(form) }}
                        
                        
                        </div>   
                </div> 
            </div>
           
            
</div>
<div></br></br></br></br></div>
<div class="row">

        <div class="container col-md-11">
            <div class="card ">
                <div class="card-header"><center style="color:red;">Liste des operations</center></div>
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <th>IDENTIFIANT</th>
                            <th>NUMERO OPERATION</th>
                            <th>TYPE OPERATION</th>
                            <th>MONTANT</th>
                            <th>DATE OPERATION</th>
                            <th>NUMERO COMPTE</th>
                            <th><center>Action</center></th>
                            
                             
                        </tr>
                        {% for c in operations %}
                       
                            <tr>
                                <td>{{ c.id }}</td>
                                <td>{{ c.numeroOperation }}</td>
                                <td>{{ c.typeOperation }}</td>
                                <td>{{ c.montant }}</td>
                                <td>{{ c.dateOperation|date('d/m/y') }}</td>
                                <td>{{ c.compte.numeroCompte}}</td>
                                
                                
                                <td><a href=""><button type="button" class="btn btn-danger">Annuler</button></a></td>
                            </tr>
                            
                        {% endfor %}
                    
                    </table>        
                </div>   
            </div>
        </div>
    </div>
    <div></br></br></br></br></div>

{% endblock %}