src/Entity/Compte.php
<?php

namespace App\Entity;

use App\Repository\CompteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CompteRepository::class)
 */
class Compte
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numeroCompte;

    /**
     * @ORM\Column(type="date")
     */
    private $dateCreation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $solde;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $etatCompte;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="comptes",cascade={"persist"})
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity=TypeCompte::class, inversedBy="comptes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type_Compte;

    /**
     * @ORM\OneToMany(targetEntity=Operation::class, mappedBy="compte")
     */
    private $operations;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comptes")
     */
    private $user;

    public function __construct()
    {
        $this->solde = "500";
        $this->etatCompte = "actif";
        $this->dateCreation = new \Datetime();
        $this->operations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroCompte(): ?string
    {
        return $this->numeroCompte;
    }

    public function setNumeroCompte(string $numeroCompte): self
    {
        $this->numeroCompte = $numeroCompte;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getSolde(): ?string
    {
        return $this->solde;
    }

    public function setSolde(string $solde): self
    {
        $this->solde = $solde;

        return $this;
    }

    public function getEtatCompte(): ?string
    {
        return $this->etatCompte;
    }

    public function setEtatCompte(string $etatCompte): self
    {
        $this->etatCompte = $etatCompte;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getTypeCompte(): ?TypeCompte
    {
        return $this->type_Compte;
    }

    public function setTypeCompte(?TypeCompte $type_Compte): self
    {
        $this->type_Compte = $type_Compte;

        return $this;
    }

    /**
     * @return Collection|Operation[]
     */
    public function getOperations(): Collection
    {
        return $this->operations;
    }

    public function addOperation(Operation $operation): self
    {
        if (!$this->operations->contains($operation)) {
            $this->operations[] = $operation;
            $operation->setCompte($this);
        }

        return $this;
    }

    public function removeOperation(Operation $operation): self
    {
        if ($this->operations->contains($operation)) {
            $this->operations->removeElement($operation);
            // set the owning side to null (unless already changed)
            if ($operation->getCompte() === $this) {
                $operation->setCompte(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/CompteType.php
<?php

namespace App\Form;

use App\Entity\Client;
use App\Entity\Compte;
use App\Entity\TypeCompte;
use App\Repository\CompteRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ResetType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CompteType extends AbstractType
{
    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
       
        
        $builder
            ->add('type_Compte',EntityType::class,array('class'=>TypeCompte::class,'label'=>'Type Compte', 'attr'=>array('class'=>'form-control form-group')))
            //->add('numeroCompte',TextType::class,array('label'=>'Numero du compte','required'=>False, 'attr'=>array('class'=>'form-control form-group')))
            //->add('dateCreation',DateType::class,array('label'=>"Date de creation", 'attr'=>array('class'=>'form-control form-group')))
            //->add('solde',TextType::class,array('label'=>'Solde','required'=>False, 'attr'=>array('class'=>'form-control form-group')))
            //->add('etatCompte',TextType::class,array('label'=>'etat compte','required'=>False, 'attr'=>array('value'=>'actif','class'=>'form-control form-group')))
            ->add('client',ClientType::class,array('label'=>'client','required'=>False))
            
            ->add('Valider', SubmitType::class, array('attr'=>array('class'=>'btn btn-success form-group')))
            ->add('Annuler', ResetType::class, array('attr'=>array('class'=>'btn btn-danger form-group')))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Compte::class,
        ]);
    }
}

src/Controller/CompteController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Repository\CompteRepository;
use App\Entity\Compte;

use App\Form\CompteType;
use App\Form\CompteType2;
use phpDocumentor\Reflection\Types\Integer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class CompteController extends AbstractController
{
    /**
     * @Route("/Compte/liste", name="compte")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();
        $p=new Compte();
        
        
     
        $form = $this->createForm(CompteType::class, $p, array('action'=>$this->generateUrl('compte_add')));
        $data['form'] = $form->createView();

        $data['comptes'] = $em->getRepository(Compte::class)->findAll();
        //$comptes = $em->getRepository(Compte::class)->findAll();
        foreach ($data['comptes'] as $compte){
            $com=$compte->getDateCreation();
            $datetime2 = new \DateTime(date("Y-m-d H:i:s")); 
        $interval = $com->diff($datetime2);
        echo $interval->format('%a');echo '-';
        
        //chaque un an le compte epargne simple est rémunérer de 5000..je teste sur un jour d'abord
        if($interval->format('%a')>=1 && $compte->getTypeCompte()->getLibelle()=='Epargne xeewel'){
            
            $soldeini= $compte->getSolde();
            echo $soldeini;die();
            $soldefinal=$soldeini+2000;
            $compte->setSolde($soldefinal);
            $em->flush();
            return $this->render('compte/liste.html.twig',$data);
        }
        //agios à retirer tous les trois mois pour les compte courant
        if($interval->format('%a')==90 && $p->getTypeCompte()->getLibelle()=='Courant'){
            
            $soldeinit= $compte->getSolde();
            $soldefina=$soldeinit-1000;
            $p->setSolde($soldefina);
            $em->flush();
        }
        
        }
        return $this->render('compte/liste.html.twig',$data);
    }

    /**
     * @Route("/Compte/add", name="compte_add")
     */
    public function add(Request $request, CompteRepository $repository)
    {
        $c = new Compte();
        $p= new Client();
        $form = $this->createForm(CompteType::class, $c);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $c = $form->getData();
            
            $dateCreation = new \Datetime();
            $c->setDateCreation($dateCreation);
            $solde='500';
            $c->setSolde($solde);
            $etat1='actif';
            $c->setEtatCompte($etat1);
            $lastid = $repository->getMaxId();//getMaxId() fonction créer dans compteRepository 
            $c->setNumeroCompte($lastid);
            $c->setUser($this->getUser());
            
            $em = $this->getDoctrine()->getManager();
            $em->persist($c);
            //$em->persist($c->getEmployeur()); soit cette ligne ou cascade={"persist"} au  niveau de l'entité
            $em->flush();
            if($c->getClient()->getUser()==null){
                $p =$em->getRepository(Client::class)->find($c->getClient()->getId());
                $p->setUser($this->getUser());
              
                $em->flush();
            }
        }
      
        return $this->redirectToRoute('compte');
    }

    /**
     * @Route("/Compte/delete/{id}", name="compte_delete")
     */
    public function delete($id)
    {
        $em = $this->getDoctrine()->getManager();
        $compte = $em->getRepository(Compte::class)->find($id);
        if ($compte != null)
        {
            $em->remove($compte);
            $em->flush();
        }
        return $this->redirectToRoute('compte');
         
    }
    /**
     * @Route("/Compte/edit/{id}", name="compte_edit")
     */
    public function edit($id)
    {
        $em = $this->getDoctrine()->getManager();
        $p = $em->getRepository(Compte::class)->find($id);

        $form = $this->createForm(CompteType2::class, $p, array('action'=>$this->generateUrl('compte_update', ['id' => $id])));
        $data['form'] = $form->createView();

        //$data['comptes'] = $em->getRepository(Compte::class)->findAll();
        return $this->render('compte/modifier.html.twig',$data);
        
        
    }

    /**
     * @Route("/Compte/update/{id}", name="compte_update")
     */
    public function update($id, Request $request)
    {
        $p = new Compte();
       
        $form = $this->createForm(CompteType2::class, $p);
        
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $p = $form->getData();
  
            $em = $this->getDoctrine()->getManager();
            $compte = $em->getRepository(Compte::class)->find($id);
            $compte->setTypeCompte($p->getTypeCompte());
            $compte->setEtatCompte($p->getEtatCompte());
            
            $em->flush();
        }
      
        return $this->redirectToRoute('compte');
    }
    /**
     * @Route("/Compte/new/{id}", name="client_AjoutCompte")
     */
    public function new($id)
    {
        $em = $this->getDoctrine()->getManager();
        //$p = $em->getRepository(Compte::class)->find($id);
        $p = new Compte();
       
        $form = $this->createForm(CompteType2::class,$p, array('action'=>$this->generateUrl('client_newCompte', ['id' => $id])));
        $data['form'] = $form->createView();

        //$data['comptes'] = $em->getRepository(Compte::class)->findAll();
        return $this->render('compte/nouveau.html.twig',$data);
        
        
    }

    /**
     * @Route("/Compte/AjoutCompte/{id}", name="client_newCompte")
     */
    public function ajoutCompte(Request $request,$id,CompteRepository $repository)
    {
        $em = $this->getDoctrine()->getManager();
        $c = new Compte();
        $p=new Client();
        
        $c->setClient($em->getRepository(Client::class)->find($id));

        $form = $this->createForm(CompteType2::class, $c);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $c = $form->getData();
            
            $dateCreation = new \Datetime();
            $c->setDateCreation($dateCreation);
            $solde='500';
            $c->setSolde($solde);
            //$etat1='actif';
            //$c->setEtatCompte($etat1);
            $lastid = $repository->getMaxId();//getMaxId() fonction créer dans compteRepository
            $c->setNumeroCompte($lastid);
            $c->setUser($this->getUser());
            $em->persist($c);
            
            $em->flush();
            if($c->getClient()->getUser()==null){
                $p =$em->getRepository(Client::class)->find($c->getClient()->getId());
                $p->setUser($this->getUser());
              
                $em->flush();
            }
        }
        return $this->redirectToRoute('compte');  
        
    }


    /**
     * @Route("/Compte/bloque/{id}", name="compte_bloquer")
     */
    public function bloquer($id, Request $request)
    {
        $p = new Compte();
        $em = $this->getDoctrine()->getManager();
        $p = $em->getRepository(Compte::class)->find($id);
        $etat1='bloquer';
        $p->setEtatCompte($etat1); 
            $em->flush();
        return $this->redirectToRoute('compte');
        
    }

    /**
     * @Route("/Compte/active/{id}", name="compte_activer")
     */
    public function activer($id)
    {
        $p = new Compte();
        $em = $this->getDoctrine()->getManager();
        $p = $em->getRepository(Compte::class)->find($id);
        $etat1='actif';
        $dateCrea=$p->getDateCreation();
        $datetime2 = new \DateTime(date("Y-m-d H:i:s")); 
        $interval = $dateCrea->diff($datetime2);
        echo $interval->format('%a');
        $duree=  $interval->format('%a');
        //var_dump($dateCrea);
        if($interval->format('%a')<90 ){
            $form = $this->createForm(CompteType::class, $p, array('action'=>$this->generateUrl('compte_add')));
        $data['form'] = $form->createView();

        $data['comptes'] = $em->getRepository(Compte::class)->findAll();
        $data['active_message']='Impossible d\'activer ce compte !!!! délai minimum requis 3mois. votre est bloqué depuis '.$duree.' jours';
        return $this->render('compte/liste.html.twig',$data);
          
        }else{
            $p->setEtatCompte($etat1); 
            $em->flush();
        return $this->redirectToRoute('compte');
        }
        die();
        
        
        
    }

}

templates/compte/liste.html.twig
{% extends 'accueil.html.twig' %}
{%block glyficon%}
<link href="{{ asset('modaal/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
<script src="{{ asset('modaal/bootstrap.min.js') }}"></script>
<script src="{{ asset('modaal/jquery-3.2.1.min.js') }}"></script>



<style>
  .modal-header, h4, .close {
    background-color: #5cb85c;
    color:white !important;
    text-align: center;
    font-size: 30px;
  }
  .modal-footer {
    background-color: #f9f9f9;
  }
  </style>
{% endblock%}
{% block title %}Gestion Compte{% endblock %}

{% block body %}

<div class="container col-md-11">
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
  Nouveau Client
</button></div>
<div></br></br></div>
<div class="row">

        <div class="container col-md-12">
            <div class="card ">
                <div class="card-header"><center style="color:red;">Liste des Comptes</center></div>
                <div class="card-body">
                {% if active_message is defined %}
                            <div class="alert alert-danger">{{ active_message  }}</div>
                        {% endif %}
                    <table class="table table-striped">
                        <tr>
                            <th>ID</th>
                            <th>NUMERO COMPTE</th>
                            <th>TYPE COMPTE</th>
                            <th>DATE CREATION</th>
                            <th>SOLDE</th>
                            <th>NOM CLIENT</th>
                            <th>Action</th>
                            <th>Action</th>
                            <th>Action</th>
                            <th>Action</th>
                            <th>Action</th>
                             
                        </tr>
                        {% for c in comptes %}
                       
                            <tr>
                                <td>{{ c.id }}</td>
                                <td>{{ c.numeroCompte }}</td>
                                <td>{{ c.typeCompte.libelle }}</td>
                                <td>{{ c.dateCreation|date('d/m/y')}}</td>
                                <td>{{ c.solde }}</td>
                                <td>{{ c.client.nom }} {{ c.client.prenom }}</td>
                               {%if c.etatCompte=='actif'%}
                                <td><a >ACTIVER</a></td>
                                <td><a href="{{ path('compte_edit', {'id':c.id}) }}"><button type="button" class="btn btn-warning">Editer</button></a></td>
                                <td><a href="{{ path('operation_edit', {'id':c.id}) }}"><button type="button" class="btn btn-success">Liste Ope</button></a></td>
                                <td><a href="{{ path('compte_delete', {'id':c.id}) }}"><button type="button" class="btn btn-danger">Delete</button></a></td>
                                <td><a href="{{ path('compte_bloquer', {'id':c.id}) }}"><button type="button" class="btn btn-primary">Bloquer</button></a></td>
                                {%else%}
                                <td><a href="{{ path('compte_activer', {'id':c.id}) }}"><button type="button" class="btn btn-primary">Activer</button></a></td>
                                <td><a href="{{ path('compte_edit', {'id':c.id}) }}"><button type="button" class="btn btn-warning">Editer</button></a></td>
                                <td><a href="{{ path('operation_edit', {'id':c.id}) }}"><button type="button" class="btn btn-success">Liste Ope</button></a></td>
                                <td><a href="{{ path('compte_delete', {'id':c.id}) }}"><button type="button" class="btn btn-danger">Delete</button></a></td>
                                <td><a>BLOQUER</a></td>
                                {%endif%}
                            </tr>
                            
                        {% endfor %}
                    
                    </table>        
                </div>   
            </div>
        </div>
    </div>
    <div></br></br></br></br></div>



<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Ajouter un client ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
            <div class="container col-md-12">
                <div class="card ">
                    <div class="card-header"><center style="color:red;">Formulaire ajout client</center></div>
                        <div class="card-body">
                      {{ form(form) }}
                        </div>   
                </div> 
            </div>
</div>
      </div>
      <div class="modal-footer">
        <div class="container my-auto">
  <div class="copyright text-center my-auto">
    <span>Copyright &copy; Banque-du-Peuple 2020</span>
  </div>
</div>
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/compte/modifier.html.twig
{% extends 'accueil.html.twig' %}

{% block title %}Gestion compte{% endblock %}

{% block body %}

<div></br></br></div>

<div class="row">
            <div class="container col-md-8">
                <div class="card ">
                    <div class="card-header"><center style="color:red;">Modification compte </center></div>
                        <div class="card-body">
                        {{ form(form) }}
                        </div>   
                </div> 
            </div>
</div>

{% endblock %}

templates/compte/nouveau.html.twig
{% extends 'accueil.html.twig' %}

{% block title %}Gestion compte{% endblock %}

{% block body %}

<div></br></br></div>

<div class="row">
            <div class="container col-md-8">
                <div class="card ">
                    <div class="card-header"><center style="color:red;">Nouveau compte </center></div>
                        <div class="card-body">
                        {{ form(form) }}
                        </div>   
                </div> 
            </div>
</div>

{% endblock %}